# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  before_all do
    ensure_git_status_clean
  end

  desc "Push a new beta build to TestFlight"
  lane :beta do
    build_app(workspace: "StreetArt.xcworkspace", scheme: "StreetArt")
    upload_to_testflight(skip_waiting_for_build_processing: true)
  end

  desc "Increment App Build Number"
  lane :update_build_number do
    increment_build_number
  end

  after_all do |lane|
    # This block is called, only if the executed lane was successful

    clean_build_artifacts(
      exclude_pattern: ".*\.mobileprovision"
    )
  end
end
